# Generated by Django 4.2 on 2023-04-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tribe',
            table='cesarsquads_tribe',
        ),
    ]
