# Generated by Django 4.2 on 2023-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSquad', models.CharField(max_length=100)),
                ('descriptionSquad', models.CharField(max_length=300)),
                ('photoSquad', models.ImageField(default='', upload_to='squad_images')),
                ('maxUsers', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTribe', models.CharField(max_length=100)),
                ('descriptionTribe', models.CharField(max_length=300)),
                ('photoTribe', models.ImageField(default='', upload_to='tribe_images')),
                ('maxSquads', models.IntegerField(blank=True)),
                ('maxUserSquads', models.IntegerField(blank=True)),
            ],
        ),
    ]
