# Generated by Django 4.2 on 2023-04-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0002_squad_tribo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tribo',
            new_name='Tribe',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='descriptionSquad',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='nameSquad',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='photoSquad',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='tribe',
            old_name='descriptionTribe',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tribe',
            old_name='maxSquads',
            new_name='max_squads',
        ),
        migrations.RenameField(
            model_name='tribe',
            old_name='maxUserSquads',
            new_name='max_user_squad',
        ),
        migrations.RenameField(
            model_name='tribe',
            old_name='nameTribe',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tribe',
            old_name='photoTribe',
            new_name='photo',
        ),
    ]
