# Generated by Django 4.2 on 2023-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0002_alter_tribe_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='tribe',
            table=None,
        ),
    ]
