# Generated by Django 4.2 on 2023-04-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0003_rename_tribo_tribe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='maxUsers',
            new_name='max_users',
        ),
    ]
