# Generated by Django 4.2 on 2023-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0004_remove_squad_tribe_alter_squad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
