# Generated by Django 4.2 on 2023-04-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0007_rename_photo_profile_profileimg_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
