# Generated by Django 4.2 on 2023-04-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0007_remove_squad_slug_remove_squad_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
