# Generated by Django 4.2 on 2023-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0009_squad_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='squad',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tribe',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='tribe',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
