# Generated by Django 4.2 on 2023-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0010_squad_avatar_squad_bio_tribe_avatar_tribe_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='squad'),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='tribe_photos'),
        ),
    ]
