# Generated by Django 4.2 on 2023-05-12 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cesarsquads', '0010_squad_avatar_squad_bio_tribe_avatar_tribe_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(related_name='squads', to=settings.AUTH_USER_MODEL),
        ),
    ]
