# Generated by Django 4.2 on 2023-05-12 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cesarsquads', '0011_squad_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='members',
            field=models.ManyToManyField(related_name='tribes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='squad',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='squad'),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='tribe'),
        ),
    ]
