# Generated by Django 4.2 on 2023-05-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0011_alter_squad_avatar_alter_tribe_avatar'),
        ('cesarsquads', '0012_tribe_members_alter_squad_avatar_alter_tribe_avatar'),
    ]

    operations = [
    ]
