# Generated by Django 4.2 on 2023-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0013_merge_20230512_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='tribe'),
        ),
    ]
