# Generated by Django 4.2 on 2023-05-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0014_alter_tribe_avatar'),
        ('cesarsquads', '0014_alter_tribe_avatar_alter_tribe_bio'),
    ]

    operations = [
    ]
