# Generated by Django 4.2 on 2023-05-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0015_merge_20230512_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tribe_search',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
