# Generated by Django 4.2 on 2023-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0015_merge_20230512_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
