# Generated by Django 4.2 on 2023-05-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesarsquads', '0016_alter_squad_bio'),
        ('cesarsquads', '0016_profile_tribe_search'),
    ]

    operations = [
    ]
